server:
  port: 4711


management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
spring:
  data:
    mongodb:
      uri: "mongodb+srv://rtanonym:k8x5OUDeao3FRech@cluster0.5cocpos.mongodb.net/?retryWrites=true&w=majority"
      database: quizgame